#!/bin/bash

source ~/.config/bash/git/prompt.sh
source ~/.config/bash/git/completion.sh
source ~/.config/bash/alias.sh
source ~/.config/bash/prompt.sh
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# cargo
export PATH="$HOME/.cargo/bin:$PATH"

# Set the editor and git editor
export EDITOR=nvim

# Set the vi mode for bash
set -o vi

# Erase duplicates in history
export HISTCONTROL=erasedups

# Store 10k history entries
export HISTSIZE=10000

# Append to the history file when exiting instead of overwriting it
shopt -s histappend

# pyenv shenanigans
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# poetry shenanigans
export PATH="$HOME/.local/bin:$PATH"
